### ISSUE TITLE
Jexactyl support

### ISSUE THREAD

**Issue by OlekAleksander** [PteroPackages/Eyrie#1]
Add support for [jexactyl game panel](https://jexactyl.com)

**Comment by devnote-dev** [comment]
Will look into it once there's a stable build. 👍

**Comment by camwhi-te** [comment]
Call me biased but that sounds like a great idea. 😎

**Comment by devnote-dev** [comment]
Implemented in 643559c6d26ace1b39746ba6415f06c45335dd8e and ce580695404ec562a5dcc77996498e69cfa37dc9. 👍
