### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by revij** [PteroPackages/Eyrie#3]
Hi, trying to test this out but I'm unable to build it.

Running on Ubuntu 20.04 with Crystal 1.5.1

```
# crystal build src/eyrie.cr -o bin/eyrie -p --release --error-trace
In src/commands/root.cr:28:9f check)

 28 | def setup
          ^----
Error: this method overrides CLI::Command#setup() which has an explicit return type of Nil.

Please add an explicit return type (Nil or a subtype of it) to this method as well.
```

I tried adding Nil return type but then get:
```
In src/commands/init.cr:2:3ef check)

 2 | class InitCommand < CLI::Command
     ^
Error: abstract `def CLI::Command#run(args : ArgsInput, options : OptionsInput)` must be implemented by Eyrie::Commands::InitCommand
```

Am I missing something?

**Comment by devnote-dev** [comment]
Hi, this seems to be an issue with the CLI shard Eyrie uses: I forgot to set the version at the time so `shards install` is installing the latest version which isn't compatible. You can try setting the CLI dependency to version 1, but I think I will have to update everything to v2.

**Comment by revij** [comment]
Thanks! Build worked fine after switch CLI on `checkout 71706e2b6c6fce7f7bb73a505147ddeed4075542` (git releases didn't include v1)

**Comment by devnote-dev** [comment]
Great to hear! I've updated Eyrie to use v2 now: d7c05ec88cffe6688388e36ea7f63a213e2a53e2, thanks for reporting this 👍
